name: Download Firmware
on:
  workflow_dispatch:
    inputs:
      fw_link:
        description: 'Input firmware link'
        required: true

jobs:
  download:
    name: Download Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Download Fw
        run: |
          wget ${{ github.event.inputs.fw_link }}
          FW_PATH=$(find ./ -name "*img.*")
          echo "FW_PATH=$FW_PATH" >> $GITHUB_ENV

      - name: Extract Fw
        run: |
          if [[ -z "${{ env.FW_PATH }}" ]]; then
              echo "Firmware path is empty. Exiting."
              exit 1
          fi

          if [[ ${{ env.FW_PATH }} == *.img.gz ]]; then
              sudo gunzip "${{ env.FW_PATH }}"
          elif [[ ${{ env.FW_PATH }} == *.img.xz ]]; then
              sudo unxz "${{ env.FW_PATH }}"
          else
              echo "Unsupported file type: ${{ env.FW_PATH }}"
              exit 1
          fi

      - name: Download Fw
        run: |
          fdisk -l *.img
          mkdir /mnt/openwrt-rootfs
          
