name: Upload Rootfs
on:
  workflow_dispatch:
    inputs:
      gd_link:
        description: 'Input googledrive link'
        required: true
jobs:
  download:
    name: Download Rootfs
    runs-on: ubuntu-latest
    steps:
      - name: Download Rootfs
        run: |
          pip install gdown
          gdown ${{ github.event.inputs.gd_link }}
          ROOTFS_PATH=$(find ./ -name "*rootfs.tar.gz")
          echo "ROOTFS_PATH=$ROOTFS_PATH" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          name: Mutiara-Wrt_23.05.5_Rootfs
          tag_name: v23.05.5
          draft: false
          prerelease: false
          files: |
                ${{ env.ROOTFS_PATH }}
          body: |
            New Rootfs
