name: Engine Spesification
on:
  workflow_dispatch:
jobs:
  check:
    name: Check Specs
    runs-on: ubuntu-latest
    steps:
      - name: Neofetch
        run: |
          sudo apt install neofetch -y
          neofetch

      - name: Speedtest
        run: |
          sudo apt install speedtest-cli -y
          speedtest
