name: Engine Spesification
on:
  workflow_dispatch:
jobs:
  check:
    name: Check Specs
    runs-on: ubuntu-latest
    steps:
      - name: Neofetch
        run: |
          sudo apt install neofetch -y > /dev/null 2>&1
          neofetch

      - name: Speedtest
        run: |
          sudo apt-get install curl > /dev/null 2>&1
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash > /dev/null 2>&1
          sudo apt-get install speedtest > /dev/null 2>&1
          speedtest
