name: Engine Spesification
on:
  workflow_dispatch:
jobs:
  check:
    name: Check Specs
    runs-on: windows-10
    steps:
      - name: Neofetch
        run: |
          sudo apt install neofetch -y
          neofetch
