name: Engine Spesification
on:
  workflow_dispatch:
jobs:
  check:
    name: Check Specs
    runs-on: ubuntu-latest
    steps:
      - name: Neofetch
        run: |
          sudo apt install neofetch -y
          neofetch

      - name: Speedtest
        run: |
          sudo apt-get install curl
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt-get install speedtest
